version: '2'

services:

    nginx:
        build: ./nginx
        volumes:
            - ${APPLICATION}:/home/docker/code/app/
        ports:
            - "80:80"
            - "443:443"
        networks:
            - backend

    django:
        build: ./django
        volumes:
            - ${APPLICATION}/api:/home/docker/code/app/
        networks:
            - backend
        depends_on:
            - nginx

    node-nuxt:
        build: ./node-nuxt
        volumes:
            - ${APPLICATION}/view-nuxt:/home/docker/code/app/
        networks:
            - backend
        depends_on:
            - nginx

    node-angular:
        build: ./node-angular
        volumes:
            - ${APPLICATION}/view-angular:/home/docker/code/app/
        networks:
            - backend
        depends_on:
            - nginx

    mongo:
        build: ./mongo
        ports:
            - "${MONGODB_PORT}:27017"
        volumes:
            - "${DATA_SAVE_PATH}/mongo:/data/db"
        networks:
            - backend

    postgres:
        build: ./postgres
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - "${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - backend

networks:
    backend:
        driver: "bridge"