version: '2'

services:

    nginx:
        build: ./nginx
        ports:
            - "80:80"
            - "443:443"
        networks:
            - backend

    django:
        build: ./django
        ports:
         - "8001:8001"
        volumes:
            - ${APPLICATION}:/home/docker/code/app/
        networks:
            - backend

    mongo:
        build: ./mongo
        ports:
            - "${MONGODB_PORT}:27017"
        volumes:
            - "${DATA_SAVE_PATH}/mongo:/data/db"
        networks:
            - backend


    node:
      build: ./node
      ports:
        - "3000:3000"
      volumes:
        - ${APPLICATION}/nuxt:/home/docker/code/app/
      networks:
            - backend
      command: npm run dev


    postgres:
        build: ./postgres
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - "${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - backend

networks:
    backend:
        driver: "bridge"