version: '2'

services:
    django-wp:
        build: ./django
        volumes:
            - ${APPLICATION}:/home/docker/code/app/
        ports:
            - "80:80"
        networks:
            - backend

    mongo:
        build: ./mongo
        ports:
            - "${MONGODB_PORT}:27017"
        volumes:
            - "${DATA_SAVE_PATH}/mongo:/data/db"
        networks:
            - backend

    node:
      build: ./node
      ports:
        - "${NODE_PORT}:${NODE_PORT}"
        - "3000:3000"
      volumes:
        - ${APPLICATION}/nuxt:/home/docker/code/app/
      networks:
            - backend

    postgres:
        build: ./postgres
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - "${DATA_SAVE_PATH}/postgres:/var/lib/postgresql/data"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - backend

networks:
    backend:
        driver: "bridge"